baseURL = "http://tech.taymor.io"
languageCode = "en-us"
title = "Caroline Taymor"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Caroline Taymor"
    description = "Software Engineer and Tech Speaker"
    githubUsername = "ctaymor"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "ruby"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/donuts/"
    name = "Donuts"
    weight = 3
[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[menu.icon]]
#   url = "mailto:me@example.com"
#    name = "envelope-o"
#   weight = 1

[[menu.icon]]
    url = "https://github.com/ctaymor/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/CarolineTaymor"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/carolinetaymor/"
    name = "linkedin"
    weight = 4
