---
baseURL: "http://tech.taymor.io"
languageCode: "en-us"
title: "Caroline Taymor"
theme: "bisl"
googleAnalytics: ""
pygmentsCodeFences: true


params:
  author: "Caroline Taymor"
  description: "I make engineering teams more effective"
  githubUsername: "ctaymor"
  accent: "purple"
  showBorder: true
  backgroundColor: "white"
  highlight: true
  highlightStyle: "solarized-dark"
  highlightLanguages: ["go", "ruby"]
  fonts: 
  - "Noto+Serif"
  - "Cinzel+Decorative"
  headshotUrl: "https://storage.googleapis.com/tech-taymor/images/headshot-250square-2016b.jpg"
  bio: |
    Taking a 12 hour, 50 manual step emergency release process that only one person knew to a 2 hour, 2 step automated process.
    Teaching effective and equitable facillitation and collaborative decisionmaking.
    Finding and addressing the communication gaps in technical team communication.
  bio2: |
    Whatever the challenges preventing your engineering team from delivering business value consistently, I can help identify the blockers and work with the team to learn how to deliver those business values.
  bio3: |
    Technically, I specialize in infrastructure, platforms, devops, and release engineering, but I work with teams accross domains to improve their effectiveness.
  availability: |
    I am availabile to work with you via consulting, facillitation workshops, paid lunch and learns and other public speaking.
  twitter: "@CarolineTaymor"
  linkedIn: carolinetaymor
  formspree: "https://formspree.io/f/mpzberal"
menu:
  main:
    - url: "/"
      name: "Home"
      weight: 1
    - url: "/posts/"
      name: "Posts"
      weight: 2
    - url: "/about/"
      name: "About"
      weight: 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
  icon:
#   - url: "mailto:me@example.com"
#     name: "envelope-o"
#     weight: 1
    - url: "https://github.com/ctaymor/"
      name: "github"
      weight: 2
    - url: "https://twitter.com/CarolineTaymor"
      name: "twitter"
      weight: 3
    - url: "https://www.linkedin.com/in/carolinetaymor/"
      name: "linkedin"
      weight: 4
